# For more information: https://laravel.com/docs/sail
version: '3'
services:
    search:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - default
            - search_net
        depends_on:
            - search_db
            - search_redis
            - search_search
    search_db:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'search_db:/var/lib/mysql'
        networks:
            - search_net
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s
    search_redis:
        image: 'redis:alpine'
        volumes:
            - 'search_redis:/data'
        networks:
            - search_net
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          retries: 3
          timeout: 5s
    search_search:
        image: 'getmeili/meilisearch:latest'
        volumes:
            - 'search_search:/data.ms'
        networks:
            - search_net
        healthcheck:
          test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
          retries: 3
          timeout: 5s
    search_mail:
        image: 'mailhog/mailhog:latest'
        networks:
            - search_net
networks:
        default:
                external: true
                name: nginx_proxy
        search_net:
                driver: bridge
volumes:
    search_db:
        driver: local
    search_redis:
        driver: local
    search_search:
        driver: local
